name: Deploy to Azure

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install

    # - name: 'Deploy to Azure'
    #   uses: azure/webapps-deploy@v2
    #   with: 
    #     app-name: GaymersModMailBot
    #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}